export default function Expressions() {
  return [
    'duas sanfonada e acaba o forró',
    'duas gaitada e o Julio faz cocoricó',
    'duas palma e acaba o parabens',
    'duas chinelada e a criança chora',
    'dois tapa eu entrego o baiano',
    'duas chacoalhadas e estoura o champanhe',
    'três pedaladas e cai a corrente',
    'duas ave maria e acaba a missa',
    'dois lepo lepo o psirico desce do palco',
    'dois “a u u aa” e acaba o fantástico',
    'três tapinha nas costa e o nenê já arrota',
    'dois passo a havaiana arrebenta',
    'três tapas e o fogueteiro entrega o baiano',
    'duas balançadas a manga cai da arvore',
    'três aceleradas acaba a gasolina',
    'três embaixadinha a bola murcha',
    'três cavalgadas e acaba a vaquejada',
    'dois haha e o fala mansa ta rindo a toa',
    'dois tapa no pandero e acaba o pagode',
    'duas vuvuzelada e acaba a copa',
    'duas chacoalhada e a varinha quebra',
    'dois alohomora e a porta abre',
    'dois acordes e acabou a sinfonia',
  ];
}
