const broxada = [
  'duas sanfonada e acaba o forró',
  'duas gaitada e o Julio faz cocoricó',
  'duas palma e acaba o parabens',
  'duas chinelada e a criança chora',
  'dois tapa eu entrego o baiano',
  'duas chacoalhadas e estoura o champanhe',
  'três pedaladas e cai a corrente',
  'duas ave maria e acaba a missa',
  'dois lepo lepo o psirico desce do palco',
  'dois “a u u aa” e acaba o fantástico',
  'três tapinha nas costa e o nenê já arrota',
  'dois passo a havaiana arrebenta',
  'três tapas e o fogueteiro entrega o baiano',
  'duas balançadas a manga cai da arvore',
  'três aceleradas acaba a gasolina',
  'três embaixadinha a bola murcha',
  'três cavalgadas e acaba a vaquejada',
  'dois haha e o fala mansa ta rindo a toa',
  'dois tapa no pandero e acaba o pagode',
  'duas vuvuzelada e acaba a copa',
  'duas chacoalhada e a varinha quebra',
  'dois alohomora e a porta abre',
  'dois acordes e acabou a sinfonia',
];

const falecimento = [
  'foi de bateu as botas',
  'bebeu e foi de sócrates',
  'conheceu a picareta de stalin',
  'foi de passeio com princesa diana',
  'foi de base',
  'foi de ralo',
  'foi de arrasta pra cima',
  'foi de comes e bebes',
  'foi de jackson five',
  'foi de olavo de carvalho',
  'foi de rainha elizabeth',
  'foi de drake & josh',
  'errou o zhonyas',
  'quebrou o tabu',
  'saiu na choquei',
  'foi de tornozelo do neymar',
  'trocou o registro sem chinelo',
  'avançou o smoke',
  'desceu de toboagua',
  'foi de F',
  'não tankou',
  'foi de wakanda forever na horizontal',
  'foi de link na bio',
  'foi jogar no vasco',
  'foi de one direction',
  'foi trabalhar na record',
  'foi de berço',
  'foi de achados e perdidos',
  'foi de livre mercado',
  'foi de arrasta pra cima',
  'errou o x do anúncio',
  'foi de deitado eternamente em berço esplêndido',
  'deixou a mãe contar até três',
  'foi de caixa',
  'escreveu Deus com d minúsculo',
  'foi comprar cigarro',
];

export default { broxada, falecimento };
